name: "Conftest"
description: "Write tests against structured configuration data using Open Policy Agent"
author: "Henrique Lobao"
branding:
  icon: "check"
  color: "green"
inputs: 
  files:
    description: "Files for Conftest to test"
    required: true
  rules:
    description: "Where to find the policy folder or file"
    default: "rules"
runs:
  using: 'docker'
  image: 'docker://hflobao/cfn-guard:latest'
  entrypoint: sh
  args:
  - -c
  - cfn-guard validate --data ${{ inputs.files }} --rules ${{ inputs.rules }}
